spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pomaranch
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#  devtools:
#    restart:
#      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties
#      enabled: true
#    livereload:
#      enabled: true